# playbook.yml
---
- hosts: all
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: app, tags: ['app'] }
    - { role: ssh, tags: ['base'] }