- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install essential packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - fail2ban
      - ufw
      - curl
      - wget
      - vim
      - htop
      - git
      - unzip
      - rsync
      - nodejs
      - npm
  async: 600
  poll: 0
  register: install_packages

- name: Wait for essential packages to be installed
  async_status:
    jid: "{{ install_packages.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 10
  delay: 30

- name: Allow SSH before enabling UFW
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Configure UFW rules
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - '80'
    - '443'
    - '3000'

- name: Configure fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
  notify:
    - restart fail2ban

- name: Create app directory
  file:
    path: /opt/nodejs-app
    state: directory
    mode: '0755'

- name: Copy application files
  copy:
    src: "{{ item }}"
    dest: /opt/nodejs-app/
  with_items:
    - app.js
    - package.json

- name: Install dependencies
  npm:
    path: /opt/nodejs-app
    state: present

- name: Setup systemd service
  template:
    src: nodejs.service.j2
    dest: /etc/systemd/system/nodejs.service
  notify:
    - restart nodejs

handlers:
  - name: restart fail2ban
    service:
      name: fail2ban
      state: restarted

  - name: restart nodejs
    service:
      name: nodejs
      state: restarted
